### ISSUE TITLE
[1.10.2][Bug] Large number of items/spells not working

### ISSUE THREAD

**Issue by jarredhawke** [RootsTeam/Roots#100]
Minecraft: v1.10.2
Roots: v0.110.0 (latest)
Forge: v2044 & v2056 (tested on both)
Other mods installed: Only JEI

I've tested out about a third of the spells/items in the mod and I've already found a huge number of bugs:
Spell Earth Spike - Doesn't do anything when cast.
Spell Insanity - Doesn't do anything when cast.
Spell Electro Spark - Strikes the block you are standing on not the one you are looking at.
Spell Water Blast - Spell modifiers don't modify this spell.
Spell Acceleration - Doesn't do anything when cast.
Growth Powder - Doesn't do anything when right clicked.

The blistering cold spell is about the only spell I've tested that actually works (including its modifiers).

**Comment by elucent** [comment]
Hmmm. Sounds like the new Forge versions are breaking things like I heard. Give me some time to update.

**Comment by elucent** [comment]
Never mind that, I spoke too soon. Using Forge v2064, with no other mods installed, I'm able to use all of these spells and items just fine. 

Considering that I can't replicate a single one of these, I'd recommend you try updating to the latest Forge and checking your logs for any kind of error messages. Otherwise, I'm sorry to say that I don't know what's going wrong. Closing this issue for now.
