### ISSUE TITLE
Bark

### ISSUE THREAD

**Issue by Pellesaxon** [RootsTeam/Roots#111]
Hi, In "All The Mods" modpack Bark doesn't drop from loggs! The loggs still brake randomly as they should so I don't know why it doesn't work!

Thankful for answers.

//Pellesaxon

**Comment by elucent** [comment]
Any kind of console output?

**Comment by ShadowGamerXY** [comment]
Singleplayer or Multiplayer?

**Comment by Pellesaxon** [comment]
Multiplayer and the server owner can see anything in console! You can join the server and test for your self.
Server Web: http://backman.enjin.com/

**Comment by elucent** [comment]
Are you using SpongeForge? I know that's Shadow's theory. All I know is that I can confirm that it works 100% as intended on every pack I have ever played the mod on (including All The Mods, though it's been at least a month since I did), on several different servers, so unfortunately I have not been able to replicate the bug.

**Comment by Pellesaxon** [comment]
Yes Sponge is the problem! We got to that conclusion yesterday. Should i report that to Sponge?

**Comment by elucent** [comment]
You should probably report it to Sponge, though I'm not sure if they'll be able to fix it quickly, since unfortunately your bug doesn't seem to have much in the way of console output.

**Comment by Stuart74** [comment]
Have referred this usse to sponge since it was reported 2 weeks ago with no reply to the issue as of yet thanks elucent for all your work great mod so far shame the guys at sponge have broken it lol
