### ISSUE TITLE
Graphical issue

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Roots#119]
When summoning sprites the 3 ingredients that are hovering over the altar will have a transparent square around them (redstone, ender pearl, etc.) while in the cloud effect from some angles but not others. I will try to attach an image example.
EDIT: It's not just when summoning sprites but most items on the altar for most rituals.
![error](https://cloud.githubusercontent.com/assets/13642054/18350425/cfec7aac-75cd-11e6-8488-0813f372275a.png)

While I'm on graphical errors I will mention the Spellweaver Lance may look good from 1st person but it looks weird from others' perspectives.  Image below makes it look like I'm holding onto the cloth hanging off the lance and not the lance. Perhaps a 90 degree clockwise rotation would work? Not sure really.
![2016-09-08_14 24 28](https://cloud.githubusercontent.com/assets/13642054/18350922/0586b414-75d0-11e6-830d-35c9e6a8ccaf.png)

**Comment by elucent** [comment]
The items rendering above the particles is an issue of render layers, I'm not sure I can fix it. Those particles coming off the altar are weirdly dark, though, I'll see if I can fix them.

As for the lance, I'm planning on leaving it as-is, because while it does look like it's floating a bit above the player's arm, it's the only way to make it look like a spear in first-person, and frankly I don't think it's a huge deal that it floats a bit in third person.

**Comment by VallenFrostweaver** [comment]
The square around the item seems to appear when items are in front of any transparent Roots item (like sprites (I had a defeated one sitting there), the mist from the altar ceremony, the Otherworld blocks, etc.).  Is it because the Minecraft textures are possibly using indexed colors perhaps and need to be RGB/CMYK? I doubt this as I don't know the first thing about Minecraft programming but from a graphic artist perspective I've run into this before with Minecraft images using indexed colors and causing a black background instead of transparent (though this seems different). Anyway, just thought I would update this one more time for you so you know it's more than just rituals but all translucent textures show the square outline of items dropped in front of them.

**Comment by elucent** [comment]
I believe it's related to the render layers Minecraft uses. Minecraft's 3D items have a good deal of transparent texture space on some of their faces, and it would seem that those items render in front of things like blocks or particles. This means that when they render transparent parts, they overwrite the pixels in front of them instead of blending properly, resulting in the transparent boxes around the floating items. This is also the reason why most transparent particles in most mods will layer behind water.

I *might* know a way to fix this, I'll test it out later today.
