### ISSUE TITLE
Many Attuned stones uncraftable (Roots 1)

### ISSUE THREAD

**Issue by Saereth** [RootsTeam/Roots#180]
Version: roots-0.208
Pack: All the Mods Expert

Currently any energized stones that use the same incense, (verdant sprig, infernal bulb, wheat and a bark) all create acceleration standing stones. The type of bark you use doesn't seem to register. If I use birch for example which should create a grower stone I still get an acceleration stone, same for all stones with only the bark variation for incense. 

This happens in SSP and MP.

ATM expert adds bark oredicting, I suspect this may potentially be the issue? Here is a copy of their roots_expert.zs script
https://hastebin.com/sowotegaza.xml

**Comment by elucent** [comment]
The bark oredicting sounds like it _might_ be the issue. I haven't seen this issue in any other packs.

I will say, it's fairly unlikely that this bug will get fixed though. I won't close the issue since, you know, it's still an open bug, but the 1.10.2 version has been almost entirely dropped while I rewrite the mod for 1.11.

**Comment by elucent** [comment]
Closing as 1.10.2 is no longer supported.
