### ISSUE TITLE
Confirmed server crash if a creeper explodes next to standing stone

### ISSUE THREAD

**Issue by chrysikitty** [RootsTeam/Roots#185]
Server crashed randomly so I reviewed all the crash logs. It said a creeper caused the crash and a player mentioned their stones were explosion proof, right after the server came back up.

So I went to the player's stones and they agreed for me to summon a creeper next to it. As soon as the creeper exploded, it crashed the server.

I am running FTB Infinity Lite 1.5.1 modpack. The version of Roots is roots-0.208.jar

I've attached copy of my crash logs.
[crash-2017-02-24_19.51.44-server.txt](https://github.com/RootsTeam/Roots/files/800910/crash-2017-02-24_19.51.44-server.txt)

**Comment by robertmaxton42** [comment]
Just wanted to check in on this, because I'm having the same issue - creeper exploded next to my standing stones, server promptly crashes.

Running Roots 0.208 on 1.10.2. Crash report attached.
[crash-2017-04-09_05.05.40-server.txt](https://github.com/RootsTeam/Roots/files/908089/crash-2017-04-09_05.05.40-server.txt)

**Comment by syntaxaire** [comment]
Could be related to #151.

**Comment by elucent** [comment]
I know how to fix this, but I'm not maintaining 1.10.2 Roots anymore.

**Comment by elucent** [comment]
Closing as 1.10.2 is no longer supported.
